### ISSUE TITLE
contos系统权限问题

### ISSUE THREAD

**Issue by kuanglu** [sqlsec/termux-install-linux#1]
大佬，我是个小菜鸡。安装启动contos系统后，默认root用户，但是操作contos系统下的文件会提示权限不足。。。是我的姿势不对吗

**Comment by sqlsec** [comment]
有具体的操作细节吗

**Comment by kuanglu** [comment]
进入系统contos系统后cd .. cd..然后mkdir test 提示权限不足

**Comment by sqlsec** [comment]
![Xnip2020-04-27_22-29-54](https://user-images.githubusercontent.com/25379234/80383779-a4f32b00-88d6-11ea-81ee-7ce0aa77fbbb.jpg)
cd ../../ 到系统根目录了 这个/ 目录是系统目录 只读目录 图片上是我的macOS的演示 也是无法创建文件夹的

**Comment by kuanglu** [comment]
是吗......谢谢大佬解答，耽误您时间了。感谢。
