### ISSUE TITLE
安装不上

### ISSUE THREAD

**Issue by xwb2000** [sqlsec/termux-install-linux#10]
出现这个错误
CANNOT LINK EXECUTABLE "sh": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit

**Comment by sqlsec** [comment]
啊这就触及到我的姿势盲区了

**Comment by xwb2000** [comment]
好像是架构啥的不一样吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "国光"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 上午9:58
收件人: "sqlsec/termux-install-linux"<termux-install-linux@noreply.github.com&gt;; 
抄送: "淺笑丶厝ㄖ凊"<1205895054@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sqlsec/termux-install-linux] 安装不上 (#10)





 
啊这就触及到我的姿势盲区了

**Comment by sqlsec** [comment]
好想是的

**Comment by xwb2000** [comment]
chroot好像没问题&nbsp; 我改用了这个&nbsp; &nbsp;proot一直没有&nbsp; 我用Utermux里面的一键安装也出了问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "国光"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 上午10:02
收件人: "sqlsec/termux-install-linux"<termux-install-linux@noreply.github.com&gt;; 
抄送: "淺笑丶厝ㄖ凊"<1205895054@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sqlsec/termux-install-linux] 安装不上 (#10)





 
好想是的

**Comment by sqlsec** [comment]
我这个脚本里面的核心镜像文件和 AnLinux 和 AndroNix 项目是一毛一样的，理论上一个不行，其他也都不行。
