### ISSUE TITLE
CentOS root用户的密码是多少？在root用户下使用sudo提示命令不存在

### ISSUE THREAD

**Issue by AlstonLicoder** [sqlsec/termux-install-linux#11]
输入sudo yum install yum-utils
提示 bash: sudo: command not found

输入rmp、vim等命令也有相同的提示

切换到普通用户再用su切换回root用户时需要输入密码，但是我才刚刚安装好并没有设置密码

**Comment by sqlsec** [comment]
sudo 目录无法使用 建议直接 root 下操作 在 root 状态下可以尝试使用 passwd 修改密码
