### ISSUE TITLE
启动ubuntu时报错

### ISSUE THREAD

**Issue by idiomer** [sqlsec/termux-install-linux#13]
启动ubuntu时报错（./start-ubuntu.sh），错误信息如下：

proot warning: can't sanitize binding "ubuntu-fs/root": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/Termux-Linux/Ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by sqlsec** [comment]
感觉是镜像安装的问题，重新安装看看呢
