### ISSUE TITLE
proot error

### ISSUE THREAD

**Issue by tangtang-garden** [sqlsec/termux-install-linux#2]
’/home/Termux-Linux/Ubuntu/ubuntu-fs/usr/bin/env’ is a 64-bit program whereas this version of proot handles 32-bit programs only

Prior info :vpid 1: terminated with signal 4

**Comment by sqlsec** [comment]
This script is only for Chinese users to simplify the operation and use, currently only supports mainstream 64-bit systems.
In google play store AnLinux，AndroNix app may help you。
