### ISSUE TITLE
Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by CasterWx** [sqlsec/termux-install-linux#3]
系统内systemctl无法使用，无法启动后台服务，请问这个安装的系统是类docker那样的吗，产生的镜像不允许在容器内运行后台服务。

```
[root@localhost ~]# docker info
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
[root@localhost ~]# systemctl start docker
Failed to get D-Bus connection: Operation not permitted
```

**Comment by sqlsec** [comment]
在系统里面运行 docker 吗？ 吃惊 这个我没有想过哎 我看了下这些系统 只是轻量的系统 跑 docker 的话 没敢想过

**Comment by CasterWx** [comment]
> 在系统里面运行 docker 吗？ 吃惊 这个我没有想过哎 我看了下这些系统 只是轻量的系统 跑 docker 的话 没敢想过

好像所有service都没办法运行，我安装的mysql也是，有点像在一个centos的docker容器里面一样，不允许在里面运行后台服务，不过docker提供了参数可以解决，我本来还想在里面用docker跑一个mc的服务器5555555

**Comment by sqlsec** [comment]
OTZ

**Comment by EndOfMaster** [comment]
这人和我想一起去了，毕竟有了docker其他的都有了。。没有的话就。。。只能一个个适配了
