### ISSUE TITLE
安装脚本的cent os里没有ps

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [sqlsec/termux-install-linux#6]
这个是信息:
[root@localhost ~]# ps
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
是我termux没配置好还是脚本有问题?

**Comment by sqlsec** [comment]
应该是系统的问题 这个系统属于阉割系统 功能和完整的 CentOS 肯定是没法比的 =,=
